[package]
name = "opendeck"
version = "2.0.0"
description = "A cross-platform desktop application for ProntoKey and Stream Deck."
authors = [ "ninjadev64" ]
license = "BSD-3-Clause"
repository = "https://github.com/ninjadev64/OpenDeck"
default-run = "opendeck"
edition = "2021"
rust-version = "1.77"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }
built = { version = "0.7", features = [ "dependency-tree", "git2" ] }

[dependencies]
# Large, fundamental libraries
tauri = { version = "1.6", features = [ "dialog-confirm", "dialog-message", "shell-execute", "shell-open", "system-tray", "devtools" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
serialport = "4.3"
tokio = { version = "1.36", features = [ "full" ] }
tokio-tungstenite = "0.21"
tiny_http = "0.12"
elgato-streamdeck = { version = "0.7", default-features = false, features = [ "async" ] }
hidapi = { version = "2.5", default-features = false, features = [ "linux-static-hidraw", "macos-shared-device", "windows-native" ] }
image = { version = "0.25", default-features = false, features = [ "bmp", "jpeg" ] }
# Smaller utility libraries
once_cell = "1.19"
futures-util = "0.3"
anyhow = "1.0"
log = "0.4"
log-panics = "2.1"
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
serde-inline-default = "0.2"
serde_with = "3.8"
os_info = "3.8"
urlencoding = "2.1"
base64 = "0.22"
reqwest = "0.12"
zip = { version = "0.6.6", default-features = false, features = [ "deflate", "zstd" ] }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
